apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-java-demo
  namespace: cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-java-demo
  template:
    metadata:
      labels:
        app: jenkins-java-demo
    spec:
      containers:
      - name: jenkins-java-demo
        image: ${ORIGIN_REPO}/${REPO}:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 9999

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-java-demo
  namespace: cicd
spec:
  ports:
  - port: 9999
    targetPort: 9999
    name: jenkins-java-demo
  selector:
    app: jenkins-java-demo
  type: LoadBalancer
